FROM boxfuse/flyway

RUN apt-get update && apt-get -y install postgresql-client

COPY /docker/wait-for-postgres.sh /wait-for-postgres.sh

RUN chmod +x /wait-for-postgres.sh

WORKDIR /flyway

ENTRYPOINT ["flyway"]

CMD ["--help"]