name: Project CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: compile project
        run: mvn clean install -DskipTests
      - name: unit tests
        run: mvn test

  integration-test:
    runs-on:
      ubuntu-latest

    services:
      keycloak:
        image: quay.io/keycloak/keycloak:15.0.1
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        ports:
          - "8180:8080"
        options: >-
          --name keycloak
          --hostname keycloak
          --health-cmd "curl --fail http://keycloak:8080 || exit 1"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5

      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: executing integration tests
        run: echo "Success" && curl http://keycloak:8080/auth

